version: "2.20"
services:
  myagent.back:
    container_name: myagent.back
    build:
      dockerfile: Dockerfile
      context: ./
    image: myagent.back:latest
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - "16860:8000"
    environment:
      SECRET_KEY: "Mm2nBQ+bdiwqAaxMpv3O491UNf3jODuE7m1FSSnQZEbzuBBmf+90FChIuNj5Q2khFjyl1vnojqSwUOUYBQkG9fktzU2dO+Wh7tGBBrCBrCETmxM1iYxcEwOQRahuhqzmsOzrnxAuGwyL52e6eTTTtykhn0PTUh2G9slnl6KvI2SeVXMZ9Q9/7CWEoyk/KXvLkZsT0nbs6xIfDjSvSLDFusqu8a902Pjny7D6fIAPn+bRSyG6JPGo1y8vkG5x/KWZpwDR2nGUY5WrfpokkUOYJ9Eu2G1H8SWCKMpf3aaBYGWLYGT0gGT8S5BSk8vnlRNkA36z3JonDo9stObgiYeQsg=="
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_TIME: 1
      REFRESH_TOKEN_EXPIRE_TIME: 1440
      DATABASE_URL: "mysql+aiomysql://my_agent:my_agent%40pwd@host.docker.internal:35306/my_agent?charset=utf8"
      DEVICE: "cpu"
      OPENAI_API_KEY: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #docker engine, gpu driver 설정등 완료 되었을 경우 사용
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]

    command: uvicorn src.ApplicationPython:app --host 0.0.0.0 --reload --port 8000 --workers 4
